### PR TITLE
Fix soundness issues with Zero-size types

### LINKED ISSUE #5: Undefined Behavior when T is zero-sized
https://github.com/Lucretiel/stowaway/blob/fb1d8d1e658d87d23ed6541bfed96850eeca2f50/src/lib.rs#L212-L217

https://github.com/Lucretiel/stowaway/blob/fb1d8d1e658d87d23ed6541bfed96850eeca2f50/src/lib.rs#L283

Per ptr::read: Note that even if T has size 0, the pointer must be non-NULL and properly aligned.

https://doc.rust-lang.org/std/ptr/fn.read.html

### PR DESCRIPTION
**Pull request by Lucretiel**
- ZSTs now just use SizeClass::Boxed, which doesn't allocate ZSTs.
- There's already a failing soundness test for ZSTs which now passes
- Simplified logic in `size_class`

Fixes #5

### CODE REVIEW

**Comment by Lucretiel** [comment]
@TyPR124 I liked your Box idea a lot; just wanted to run this by you before merging. Thanks for the failing ZST test!

**Comment by TyPR124** [comment]
Your changes look good to me. Thanks!

About one of the comments I saw, it's a bit hard to find since most of Box's docs are at the module level, but I found that Box::new [does specify](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.new) that "this doesn't actually allocate if T is zero-sized."

One thing I did notice is I forgot to add `#[repr(C)]` to my test structs `Gaps32` and `Gaps64`. Can you add `#[repr(C)]` to the top of each of those structs? I think they will probably always have uninit bytes, but technically rust can change the layout of that struct at-will, whereas with `#[repr(C)]` it is guaranteed to leave gaps in the layout.

**Comment by Lucretiel** [comment]
Will add in a mainline commit

**Comment by Lucretiel** [comment]
Done

**Comment by Lucretiel** [comment]
Published 1.1.2

**Pull request merged**
